// Renders assets/brand/tokens.json into the stylesheet both apps load first,
// src/ui/tokens.css. tokens.test.ts holds the committed file to this output,
// and `just design-tokens` rewrites it.
//
// The renderer refuses a malformed table rather than emitting it: a light
// scheme role with no dark value, a preset role that Dusk does not declare, or
// a value that is not a colour. Each of those would render as CSS and fail
// quietly in one theme.

type Notes = { $comment?: string }
export type Tokens = {
  brand: Notes & Record<string, { hex: string; name?: string; use: string } | string | undefined>
  panel: Notes & {
    schemes: { light: Record<string, string>; dark: Record<string, string> }
    shared: Notes & Record<string, string | undefined>
  }
  stage: Notes & { presets: Record<string, Notes & Record<string, string | undefined>> }
}

const COLOUR = /^(#[0-9a-fA-F]{6}|rgba\(\s*\d+,\s*\d+,\s*\d+,\s*[\d.]+\s*\))$/

// The entries of a block, without its $comment.
function entries<T>(block: Notes & Record<string, T | string | undefined>): Array<[string, T]> {
  return Object.entries(block).filter(([k]) => k !== '$comment') as Array<[string, T]>
}

function colour(where: string, v: unknown): string {
  if (typeof v !== 'string' || !COLOUR.test(v)) throw new Error(`${where} is ${JSON.stringify(v)}, not a colour`)
  return v
}

// A CSS comment, wrapped at 76 columns and indented to the block.
function comment(text: string | undefined, indent: string): string[] {
  if (!text) return []
  const lines: string[] = []
  let line = ''
  for (const word of text.split(/\s+/)) {
    if (line && (indent + '   ' + line + ' ' + word).length > 76) {
      lines.push(line)
      line = word
    } else line = line ? `${line} ${word}` : word
  }
  lines.push(line)
  return lines.map((l, i) => `${indent}${i === 0 ? '/* ' : '   '}${l}${i === lines.length - 1 ? ' */' : ''}`)
}

export function renderTokensCss(t: Tokens): string {
  const out: string[] = [
    '/* Generated from assets/brand/tokens.json. Do not edit this file. Edit the',
    '   JSON, run `just design-tokens`, and commit both files. */',
    '',
    ':root {',
  ]

  out.push(...comment(t.brand.$comment, '  '))
  for (const [key, b] of entries<{ hex: string }>(t.brand)) out.push(`  --brand-${key}: ${colour(`brand.${key}`, b.hex)};`)

  out.push('', ...comment(t.panel.$comment, '  '))
  const { light, dark } = t.panel.schemes
  for (const role of Object.keys(light)) {
    if (!(role in dark)) throw new Error(`panel.schemes.light.${role} has no dark value`)
  }
  for (const role of Object.keys(dark)) {
    if (!(role in light)) throw new Error(`panel.schemes.dark.${role} has no light value`)
  }
  for (const role of Object.keys(light)) {
    out.push(`  --c-${role}-light: ${colour(`panel.schemes.light.${role}`, light[role])};`)
    out.push(`  --c-${role}-dark: ${colour(`panel.schemes.dark.${role}`, dark[role])};`)
  }
  out.push(...comment(t.panel.shared.$comment, '  '))
  for (const [key, v] of entries<string>(t.panel.shared)) out.push(`  --${key}: ${colour(`panel.shared.${key}`, v)};`)

  const { dusk, ...others } = t.stage.presets
  if (!dusk) throw new Error('stage.presets.dusk, the base preset, is missing')
  out.push('', ...comment(t.stage.$comment, '  '))
  for (const [key, v] of entries<string>(dusk)) out.push(`  --stage-${key}: ${colour(`stage.presets.dusk.${key}`, v)};`)
  out.push('}')

  for (const [name, preset] of Object.entries(others)) {
    out.push('', ...comment(preset.$comment, ''), `:root[data-theme='${name}'] {`)
    for (const [key, v] of entries<string>(preset)) {
      if (!(key in dusk)) throw new Error(`stage.presets.${name}.${key} has no Dusk value to fall back to`)
      out.push(`  --stage-${key}: ${colour(`stage.presets.${name}.${key}`, v)};`)
    }
    out.push('}')
  }
  return out.join('\n') + '\n'
}
